/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.flink.hadoopcompatibility.mapreduce.example.avro.java;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AminoAcidType { 
  ALIPHATIC, HYDROXYL, CYCLIC, AROMATIC, BASIC, ACIDIC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AminoAcidType\",\"namespace\":\"org.apache.flink.hadoopcompatibility.mapreduce.example.avro.java\",\"symbols\":[\"ALIPHATIC\",\"HYDROXYL\",\"CYCLIC\",\"AROMATIC\",\"BASIC\",\"ACIDIC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
