/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.flink.hadoopcompatibility.mapreduce.example.avro.java;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface FlinkParquetAvro {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"FlinkParquetAvro\",\"namespace\":\"org.apache.flink.hadoopcompatibility.mapreduce.example.avro.java\",\"types\":[{\"type\":\"enum\",\"name\":\"AminoAcidType\",\"symbols\":[\"ALIPHATIC\",\"HYDROXYL\",\"CYCLIC\",\"AROMATIC\",\"BASIC\",\"ACIDIC\"]},{\"type\":\"record\",\"name\":\"AminoAcid\",\"fields\":[{\"name\":\"type\",\"type\":\"AminoAcidType\"},{\"name\":\"fullName\",\"type\":\"string\"},{\"name\":\"abbreviation\",\"type\":\"string\"},{\"name\":\"molecularWeight\",\"type\":\"float\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends FlinkParquetAvro {
    public static final org.apache.avro.Protocol PROTOCOL = FlinkParquetAvro.PROTOCOL;
  }
}
